In [4]:
import time #libreria para medicion de tiempo
import numpy as np

# Tamaño del array
N = 1000000

# Crear una lista de Python y un array de numpy con los mismos datos
lista_python = list(range(N))
array_numpy = np.arange(N)

In [5]:
# Multiplicación usando listas de Python
start_time = time.time()
resultado_python = [x * 2 for x in lista_python]
end_time = time.time()
tiempo_python = end_time - start_time
print(f"Tiempo usando listas de Python: {tiempo_python:.10f} segundos")

Tiempo usando listas de Python: 0.1120457649 segundos


In [6]:
# Multiplicación usando arrays de NumPy
start_time = time.time()
resultado_numpy = array_numpy * 2
end_time = time.time()
tiempo_numpy = end_time - start_time
print(f"Tiempo usando arrays de NumPy: {tiempo_numpy:.10f} segundos")


Tiempo usando arrays de NumPy: 0.0019617081 segundos


In [7]:
# Calcular cuántas veces más rápido es NumPy
factor_velocidad = tiempo_python / tiempo_numpy
print(f"NumPy es aproximadamente {factor_velocidad:.2f} veces más rápido que Python puro")

NumPy es aproximadamente 57.12 veces más rápido que Python puro


In [8]:
lista = [12,36,54,85,26,34]
lista_listas = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
lista_listas_listas = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]]

# elemento mas simple en numpy....el array!



In [24]:
array1 = np.array(lista)
array2 = np.array(lista_listas, dtype="int64")
array3 = np.array(lista_listas_listas)

In [16]:
array1

array([12, 36, 54, 85, 26, 34])

In [17]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
array3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [ ]:
# cuantas dimensiones puede tener? muchisimas! pero nosotros trabajaremos con 1, 2 o 3 (esta ultima casi nunca)


In [25]:
# muchos metodos para conocer su estructura! size,shape,ndim,dtype

array2.dtype

dtype('int64')

In [32]:
# podemos crear arrays vacios

arr_empty = np.empty((2,3))
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# crear arrays con ceros o unos 


arr_cero = np.zeros((3,4))
arr_cero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
arr_unos = np.ones((3,4),dtype="int64")
arr_unos

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [39]:
arr_unos.dtype

dtype('int64')

In [41]:
# crear arrays con valores secuenciales


#range!!!

val_seq = np.arange(0,20,3)
val_seq

array([ 0,  3,  6,  9, 12, 15, 18])

In [45]:
val_seq2 = np.append(val_seq, 999)
val_seq2

array([  0,   3,   6,   9,  12,  15,  18, 999])

In [46]:
val_rep = np.reshape(val_seq2,(2,4))
val_rep

array([[  0,   3,   6,   9],
       [ 12,  15,  18, 999]])

In [44]:
np.append?

Signature: np.append(arr, values, axis=None)
Docstring:
Append values to the end of an array.

Parameters
----------
arr : array_like
    Values are appended to a copy of this array.
values : array_like
    These values are appended to a copy of `arr`.  It must be of the
    correct shape (the same shape as `arr`, excluding `axis`).  If
    `axis` is not specified, `values` can be any shape and will be
    flattened before use.
axis : int, optional
    The axis along which `values` are appended.  If `axis` is not
    given, both `arr` and `values` are flattened before use.

Returns
-------
append : ndarray
    A copy of `arr` with `values` appended to `axis`.  Note that
    `append` does not occur in-place: a new array is allocated and
    filled.  If `axis` is None, `out` is a flattened array.

See Also
--------
insert : Insert elements into an array.
delete : Delete elements from an array.

Examples
--------
>>> np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
array([1, 2, 3, ..., 7, 8, 

In [67]:
# crear arrays aleatorios

alea1 = np.random.randint(5,10,(2,4))
alea1

array([[5, 6, 5, 5],
       [6, 5, 8, 9]])

In [72]:
alea2 = np.random.rand(2,4)
alea2

array([[3.77662167e-01, 3.70911085e-04, 5.85872630e-02, 1.07750537e-01],
       [8.12350676e-01, 3.60100863e-01, 5.09944117e-01, 6.25569919e-01]])

In [70]:
alea3 = np.random.random_sample((2,4))
alea3

array([[0.08205877, 0.92894723, 0.76523332, 0.25873875],
       [0.16244386, 0.10422598, 0.16595984, 0.17268453]])

In [56]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [87]:
# indexacion en matrices unidemensionales y multidimensionales

array3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [91]:
array3[0,1,2:4]

array([8, 9])

In [100]:
# mascara booleana

mascara = (array2>4) & (array2<8)

array2[mascara]

array([5, 6, 7], dtype=int64)

In [96]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [102]:
# where

#cambio = np.where(condicion, valor_si_es cierto, valor_si_es falso)

cambio = np.where(mascara, "verdadero", "falso")
cambio

array([['falso', 'falso', 'falso', 'falso', 'verdadero'],
       ['verdadero', 'verdadero', 'falso', 'falso', 'falso']], dtype='<U9')

In [ ]:
# operaciones



In [103]:
# funciones
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [110]:
std_array = np.std(array2,axis=1)
std_array

array([1.41421356, 1.41421356])

In [111]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [114]:
# operaciones aritmeticas

max_arr = np.sum(array2)
max_arr

55

In [115]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [117]:
# otras operaciones

aplanado = array2.copy()
aplanado

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [118]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int64)

In [119]:
# swapaxes

cambio = np.swapaxes(array2,0,1)
cambio

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]], dtype=int64)

In [120]:
array3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [122]:
array3.shape

(2, 2, 5)

In [126]:
array3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [130]:
# 3d 

cambio = np.swapaxes(array3,1,2)
cambio

array([[[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]],

       [[11, 16],
        [12, 17],
        [13, 18],
        [14, 19],
        [15, 20]]])

In [131]:
cambio.shape

(2, 5, 2)